with-expecter: True
issue-845-fix: True
resolve-type-alias: False
dir: mocks/{{ replaceAll .InterfaceDirRelative "internal" "internal_" }}
mockname: "{{.InterfaceName}}"
outpkg: "mocks"
filename: "{{.InterfaceName}}.go"
all: True
packages:
  github.com/KyKyPy3/clean/internal/application/core:
    config:
      recursive: True
  github.com/KyKyPy3/clean/internal/modules/registration/application:
    config:
      recursive: True
  github.com/KyKyPy3/clean/internal/modules/user/infrastructure/controller/http/v1:
    config:
      recursive: True
