# Builder
FROM golang:1.23.3-alpine3.20 as builder

RUN apk update && apk upgrade && \
    apk --update add git make bash build-base tzdata && \
    mkdir /app && \
    mkdir /app/config

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN make build

RUN addgroup -S clean && adduser -S clean -G clean
RUN chmod +x /app/clean
USER clean

ENV config=config/config-test.yml

EXPOSE 8080

ENTRYPOINT ["/app/clean"]
