// Code generated by mockery v2.49.0. DO NOT EDIT.

package mocks

import (
	context "context"

	core "github.com/KyKyPy3/clean/internal/application/core"
	mock "github.com/stretchr/testify/mock"
)

// QueryHandler is an autogenerated mock type for the QueryHandler type
type QueryHandler struct {
	mock.Mock
}

type QueryHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *QueryHandler) EXPECT() *QueryHandler_Expecter {
	return &QueryHandler_Expecter{mock: &_m.Mock}
}

// Handle provides a mock function with given fields: _a0, _a1
func (_m *QueryHandler) Handle(_a0 context.Context, _a1 core.Query) (any, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Handle")
	}

	var r0 any
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, core.Query) (any, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, core.Query) any); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(any)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, core.Query) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// QueryHandler_Handle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Handle'
type QueryHandler_Handle_Call struct {
	*mock.Call
}

// Handle is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 core.Query
func (_e *QueryHandler_Expecter) Handle(_a0 interface{}, _a1 interface{}) *QueryHandler_Handle_Call {
	return &QueryHandler_Handle_Call{Call: _e.mock.On("Handle", _a0, _a1)}
}

func (_c *QueryHandler_Handle_Call) Run(run func(_a0 context.Context, _a1 core.Query)) *QueryHandler_Handle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(core.Query))
	})
	return _c
}

func (_c *QueryHandler_Handle_Call) Return(_a0 any, _a1 error) *QueryHandler_Handle_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *QueryHandler_Handle_Call) RunAndReturn(run func(context.Context, core.Query) (any, error)) *QueryHandler_Handle_Call {
	_c.Call.Return(run)
	return _c
}

// NewQueryHandler creates a new instance of QueryHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewQueryHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *QueryHandler {
	mock := &QueryHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
